config/routes.rb
Rails.application.routes.draw do
  root "static_pages#top"
  get 'static_pages/subpage', to: 'static_pages#subpage'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def top
  end

  def subpage
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title(title = '')
    base_title = 'FlowThing'
    title.present? ? "#{title} | #{base_title}" : base_title
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= page_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <%= render 'shared/flash_message' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>">
    <%= message %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <p>フッター</p>
</footer>

app/views/shared/_header.html.erb
<header class='text-center'>
  <p>ヘッダー</p>
</header>

app/views/static_pages/subpage.html.erb
<div class='center-text fabric canvasitem'>
  <div>
    <%= link_to t('.top'), root_path, class: "btn btn-outline-primary" %>
  </div>

  <div class="canvas-container-parent">
    <canvas id="fabricCanvas6" class="myCanvas" width="500" height="250"></canvas><br>
  </div>
  <div class="canvas-container-parent">
    <label>Choose Brush Color:</label>
    <input type="color" id="brushColorPicker" value="#000000"><br>
  </div>

  <div class="canvas-container-parent">
    <div class="d-flex">
      <div class="pr-2">
        <div id="brushSizePreview" style="border: 1px solid black; width: 50px; height: 50px; border-radius: 50%;"></div>
        <span id="brushSizeValue">5</span>px
        <br>
        <label>Brush Size (0.1 - 20):</label>
        <input type="range" id="brushSizePicker" min="0.1" max="20" step="0.1" value="5">
      </div>
      <div>
        <div id="eraserSizePreview" style="border: 1px solid black; width: 50px; height: 50px; border-radius: 50%;"></div>
        <span id="eraserSizeValue">5</span>px
        <br>
        <label>Eraser Size (0.1 - 30):</label>
        <input type="range" id="eraserSizePicker" min="0.1" max="30" step="0.1" value="5">
      </div>
    </div>
  </div>

  <div class="canvas-container-parent">
    <div class="d-flex">
      <div class="pr-2">
        <button id="usePenTool">Use Pen Tool</button>
      </div>
      <div class="pr-2">
        <button id="useEraserTool">Use Eraser Tool</button>
      </div>
      <div>
        <button id="useRectangleTool">Draw Rectangle</button>
      </div>
    </div>
  </div>

  <canvas id="canvas3" width="600" height="400"></canvas><br>
</div>

app/views/static_pages/top.html.erb
<div class='text-center pt-5 buttonitem'>
  <div class='try'>
    <h1 class='fw-bold'><%= t('.title', locale: :en) %></h1><br>
  </div>

  <%= link_to t('.memo'), static_pages_subpage_path, class: "default-button green-button green-button:hover green-button:focus" %>

</div>